### ISSUE TITLE
Planejamento para 2017 \o/

### ISSUE THREAD

**Issue by clovisdasilvaneto** [css-brasil/css-brasil#4]
Comentem na issue, qual idéias vocês acham interessante de desenvolvermos e/ou compartilharmos em 2017 em pro do nosso tão querido e amado CSS <3

**Comment by afonsopacifer** [comment]
Estou separando minhas ideias aqui.. mas já quero invocar a @daliannyvieira!

**Comment by clovisdasilvaneto** [comment]
Show, e eu invoco o @jeffersonmourak , vamos dominar o mundo? ahuhauhauhauhauha

**Comment by jeffersonmourak** [comment]
## Saiu da jaula o mostro...

cheguei... e aew galera, minhas ideias pra 2017 são focar em CSS Animations e SVG haha 😃

**Comment by clovisdasilvaneto** [comment]
@jeffersonmourak massa, tu tem alguma idéia de como podemos evangelizar isso, tipo através de algum projeto novo, post no css brasil ou meetups e hangouts?

**Comment by daliannyvieira** [comment]
Eu ainda percebo a importância em bater em tecla velha: ensinar o básico com mais clareza aos iniciantes. Criar mais coisas em pt-br, mostrar que escrever CSS é divertido e não esses bloquinhos quebrados que os haters dizem ser

**Comment by jeffersonmourak** [comment]
concordo com a @daliannyvieira, Tem muita gente aqui no RN que acha CSS o inferno... Seria bom tipo se a gente criasse uma serie de posts mostrando coisas básicas para iniciantes... isso ajudaria a chamar uma galera pra o blog.

**Comment by jeffersonmourak** [comment]
@clovisdasilvaneto eu ainda não tive nenhuma ideia pra evangelizar em 2017, mas como já tinha falado pra vc estamos organizando o CSSDay aqui em natal... mas seria uma boa em 2017 a gente investir nessa parte de meetups.

**Comment by clovisdasilvaneto** [comment]
@daliannyvieira sobre disponibilizar material pt-BR agente pode criar um esquema de tags lá no blog, ou até mesmo criar um menu com o titulo "para iniciantes" com post's especificos para essa galera, o que acham?

**Comment by jeffersonmourak** [comment]
Acho massa @clovisdasilvaneto 😄

**Comment by clovisdasilvaneto** [comment]
@jeffersonmourak Essa idéia de meetups eu acho show de bola! Agente poderia criar uma organização no próprio site do Meetup com o nome CSS Brasil (não sei se já tem) e ir fazendo vários meetups nas regiões da gente através desta organização. Tipo um FEMUG que rola em vários lugares do Brasil. O que Acham @afonsopacifer, @jeffersonmourak, @daliannyvieira ?

**Comment by daliannyvieira** [comment]
Acho que seria muito bom criar a seção @clovisdasilvaneto a ideia dos meetups também!

**Comment by daliannyvieira** [comment]
Ahh e pensando em algo mais avançado. O que eu tô estudando enquanto frontender e gostaria de ver por aqui tb sao coisas mais avançadas envolvendo css + svg mesmo

**Comment by afonsopacifer** [comment]
Então.. acho inútil escrever posts sobre o básico do CSS, uma vez que temos muito desse conteúdo com qualidade em pt-br (no site do [Maujor](http://www.maujor.com/index.php) por exemplo), tbm acho desnecessário começar a criar meetups, etc.. se já existem o [meetup CSS](https://github.com/raphaelfabeni/css-sp) (em SP).. o que podemos fazer e nos unir e quem sabe levar esse meetup ja consagrado para outros estados.. isso sim seria muito irado..

Meu ponto é: Não precisamos criar tudo.. muita coisa já existe, nos podemos focar em ajudar a divulgar isso.. melhorar seus conteúdos e nos unir para tornar tudo mais forte.

**Minhas ideias:**
- Posso falar tanto com o Maujor quanto com o pessoal do Meetup de CSS para fazermos essas parcerias.. ps: Acho que seria uma grande honra ter o Maujor do nosso lado nessa missão, já que ele foi o primeiro evangelista CSS do Brasil e um dos primeiros do mundo.
- Podemos criar uma seção no blog, listando os assuntos básicos e intermediários relacionados a CSS e listar os posts que existem e são muito bons por sinal.
- Podemos organizar o conteúdo que não temos disponível e criar um calendário de postagens.. e ir criando aos poucos os artigos para preencher essas brechas (como CSS + SVG por exemplo).
- Tem o meu [canal no youtube](https://www.youtube.com/channel/UC9d_htYmYYFUXB2vBKx4NgA) que fica a disposição tbm.

Acho que o principal problema hoje, é que o conteúdo com sobre CSS está espalhado por ai. podemos reunir e organizar isso, além de gerar nosso próprio conteúdo para preencher o que faltar.

Uma ideia de projeto legal.. é fazer algo como [essa lista do CSS Tricks](https://css-tricks.com/almanac/), porém em pr-be claro, dessa forma já teremos uma grande referência em pr-bt organizada, se bem que temos o [MDN](https://developer.mozilla.org/pt-BR/docs/Web/CSS/CSS_Reference) tbm.. ai temos que pensar se vale a pena contribuir traduzindo lá ou criar nosso própria referencia.

**Comment by daliannyvieira** [comment]
Agrupar o que já existe não é má ideia @afonsopacifer agora a questão é: agrupar direito, traduzir as coisas com clareza, etc. Por que se for analisar, a grande maior parte das pessoas que não sabem/não gostam de CSS foi porque não entendeu o básico e fica se perdendo, quebrando layout.
Ah traz Maujour sim, por favor! Grande professor de todos nós

**Comment by afonsopacifer** [comment]
@daliannyvieira concordo com você, esse básico faz muita falta por ai.. as pessoas aprender a syntax e depois ficam na tentativa e erro, sem "se dar ao trabalho" de entender o qu está acontecendo ou recorrendo a Frameworks zuados..

Podemos organizar tudo em tópicos, e dividir por nível tbm.. criando uma espécie de [JavaScript The Right Way](http://jstherightway.org/pt-br/), assim sempre que alguem quiser aprender CSS, teremos o Guia Definitivo para mandar para a pessoa aprender direito.. oq vcs acham?

**Comment by clovisdasilvaneto** [comment]
Boa idéia @afonsopacifer

**Comment by clovisdasilvaneto** [comment]
@daliannyvieira e @jeffersonmourak irei adicionar vocês como membros na organização do CSS Brasil tá? =D

**Comment by clovisdasilvaneto** [comment]
@daliannyvieira, @jeffersonmourak, @afonsopacifer criei um time com o nome _Alpha Team_ e coloquei vocês lá, também criei um quadro para atividades: https://github.com/orgs/css-brasil/projects/1 Vamos usar SCRUM <3

**Comment by clovisdasilvaneto** [comment]
@daliannyvieira fiquei sabendo que tu manja dos paranaues do design, será que dava pra criar uma  identidade vizual pro CSS Brasil, baseada no site? Pois tenho a ideia de futuramente criar stickers e etc...

**Comment by afonsopacifer** [comment]
Eu não sou designer nem manjo dos paranaues de conceitos e tal.. mas posso ajudar no que der.. vamos nos basear na logo atual mesmo.. certo?

**Comment by clovisdasilvaneto** [comment]
@afonsopacifer show! That's right

**Comment by danilovaz** [comment]
Vou entrar de gaiato e dar uns pitaco. À vontê pra me mandar zarpar :joy: :heart: 

O ponto da @daliannyvieira sobre o básico de CSS é válido, uma vez que CSS é tão básico mas tão básico que o pessoal ainda insiste em:
![q3cug29](https://cloud.githubusercontent.com/assets/1218337/20161653/e883227a-a6d6-11e6-925e-504a3128c526.gif)

E tem gente que acha que dá para programar em CSS...enfim.

Porém, entra no ponto que o @afonsopacifer abordou: temos uma enciclopédia viva chamada [Maujor](http://www.maujor.com/index.php) e o próprio MDN que tem algumas coisas traduzidas, já ajuda nisso.

Então que diabos :smiling_imp: é possível fazer para evangelizar CSS da forma correta, apontando para especificações mais detalhadas (como W3C, Maujor, MDN, Almanac CSS Trikcs, etc) mas ao mesmo tempo ensinando algo prático?

Eu imagino que o ponto é: aliar a explicação do conceito com exemplos práticos que vemos corriqueiramente. Um bom ponto de inspiração, são os artigos do Marco Bruno falando de posicionamento CSS:

[Pare de chutar e aprenda as propriedades CSS de posicionamento](https://blog.frontux.com/pare-de-chutar-e-aprenda-as-propriedades-css-de-posicionamento-603154655121#.5myar3wqo)

Dessa forma conseguimos pegar Flexbox, Grids, SVG+Animação e whatever, explicar a parte de especificação e conceito de forma resumida e partir para exemplo prático, sempre mostrando outros caminhos que podem ser utilizados.

Por exemplo, centralizar verticalmente/horizontalmente. Em 2007 existia 1 forma de se fazer isso. Hoje existem, no mínimo, 3 formas de se fazer isso. Dá para ensinar as 3 formas, explicar quando é melhor usar uma ou outra e por que/como funciona aquele comportamento.

Para isso seria legal:
- Meetups: Não precisa criar um específico, pois, já existe todo o know-how do Meetup CSS, pode ser o caso de conversar com o Felipe e o Raphael. Seria uma boa tentar levar para outras cidades. Aqui em SJC eu e um designer, queríamos sacudir a parte de Front+UX da região, conversamos com o Matheus e o Gui e hoje rola FrontUX - SJC;
- Blog: Medium ou dentro do CSSBrasil.org (como já existe);
- Codepen: Embedar os exemplos e separar por Collections (além de Codepen ser :heart:, já traz um pessoal novo pra conhecer/usar);
- Newsletter: Uma curadoria de inspirações, utilidades, novas implementações dos browsers, especificações...etc. Precisa de braço, muito braço. Mas é muito válido;
- Desafios: O @afonsopacifer faz uns desafios CSS às vezes, essa ideia é muito boa pra instigar o pessoal à estudar/brincar/desbravar algo novo apresentado pelo CSSBrasil;
- Youtube: o @afonsopacifer tem um canal e seria legal rolar uma sessão de basics CSS por lá. Se a demanda aumentar, cria-se um canal do CSSBrasil no Youtube. Provavelmente um item a ser visto por último, visto que a produção de vídeo demanda muito mais tempo do que escrever um post

_Sempre textão, desculpem_ :disappointed:

**Comment by clovisdasilvaneto** [comment]
Como não temos mais movimentação no tópico e mais nenhuma idéia foi levantada estarei fechando a issue.
